version: "3"

services:
  api:
    build: ./docker/api
    working_dir: /go/src/github.com/chonla/oddsvr
    command: go run main.go
    ports:
      - 8080:8080
    links:
      - db
    environment:
      - ODDSVR_STRAVA_CLIENT_ID=30053
      - ODDSVR_STRAVA_CLIENT_SECRET=c8066cb7fe0d47a197b3f1932e85d7f8a8e1f4ae
      - ODDSVR_JWT_SECRET=WhyWhoWhatHow
      - ODDSVR_DB=oddsvradmin:oddsvrpassword@db:27017
      - ODDSVR_ADDR=0.0.0.0:8080
  web:
    build: ./docker/web
    ports:
      - 80:80
    volumes:
      - .:/src
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=oddsvradmin
      - MONGO_INITDB_ROOT_PASSWORD=oddsvrpassword